In [1]:
import findspark
findspark.init()

In [2]:
import sys
sys.path.append("../")

In [3]:
from src.utils import create_spark_session, load_data, count_distinct_values, count_missing_values
from pyspark.sql.functions import col, when

In [4]:
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
spark = create_spark_session()

In [6]:
books = load_data(spark, "../data/raw/Books.csv")
rates = load_data(spark, "../data/raw/Ratings.csv")
users = load_data(spark, "../data/raw/Users.csv")

## Exploration Books.csv

In [ ]:
books.toPandas()

In [ ]:
books.printSchema()

In [ ]:
count_distinct_values(books).show()

In [ ]:
count_missing_values(books).show()

In [ ]:
print(f"Nombres de lignes dupliqués : {books.toPandas().duplicated().sum()}")

In [ ]:
annee_min_valide = 1900
annee_max_valide = 2022

# Filtrer les années valides et non valides
annees_valides = books.filter((col("Year-Of-Publication").isNotNull()) & (col("Year-Of-Publication").between(annee_min_valide, annee_max_valide)))
annees_non_valides = books.filter(~((col("Year-Of-Publication").isNotNull()) & (col("Year-Of-Publication").between(annee_min_valide, annee_max_valide))))

# Collecter les résultats
liste_annees_valides = annees_valides.select("Year-Of-Publication").distinct().collect()
liste_annees_non_valides = annees_non_valides.select("Year-Of-Publication").distinct().collect()

# Afficher les résultats
print("Liste des années valides (", annees_valides.count(),"):", [row["Year-Of-Publication"] for row in liste_annees_valides])
print("Liste des années non valides (", annees_non_valides.count(),") :", [row["Year-Of-Publication"] for row in liste_annees_non_valides])

In [ ]:
annees_valides = annees_valides.withColumn("Year-Of-Publication", annees_valides["Year-Of-Publication"].cast("integer"))

plt.figure(figsize=(20,10))
sns.countplot(x=annees_valides.toPandas()['Year-Of-Publication'])
plt.xticks(rotation=90)
plt.show()

La majorité des livres a été publié entre 1980 et 2004

## Exploration Rates.csv

In [ ]:
rates.toPandas()

In [ ]:
rates.printSchema()

In [ ]:
count_distinct_values(rates).show()

In [ ]:
count_missing_values(rates).show()

In [ ]:
rates_count = rates.groupby("Book-Rating").count()

In [ ]:
rates_count.toPandas().plot(kind="bar", x='Book-Rating', y='count')

Il est courant dans les systèmes de recommandation de disposer de données de rétroaction implicite, où les utilisateurs ne fournissent pas explicitement de notes, mais où leurs actions peuvent être utilisées comme une indication de préférence. Dans ce cas, une note de 0 pourrait représenter une note manquante ou inconnue, qui est souvent traitée comme un "retour négatif implicite". Cela signifie que les utilisateurs qui n'ont pas fourni de note pour un livre n'indiquent pas nécessairement qu'ils n'aiment pas le livre ; ils n'ont peut-être tout simplement pas exprimé d'opinion à ce sujet.

In [ ]:
print(f"Nombres de lignes dupliqués : {rates.toPandas().duplicated().sum()}")

## Exploration Users.csv

In [ ]:
users.toPandas()

In [ ]:
count_distinct_values(users).show()

In [ ]:
count_missing_values(users).show()

In [ ]:
print(f"Nombres de lignes dupliqués : {books.toPandas().duplicated().sum()}")

In [25]:
"""
from src.preprocessing import preprocess_ratings
pre_rate = preprocess_ratings(rates, nb=500)
pre_rate.toPandas()
rating_counts_per_user = pre_rate.groupBy('User-ID').agg(F.count('Book-Rating').alias('num_ratings_per_user'))
rating_counts_per_user.show()

pdr = pre_rate.toPandas()
x = pdr["User-ID"].value_counts()>200
y = x[x].index
y.shape
"""
print()

In [26]:
from src.preprocessing import preprocess

In [27]:
preprocessed = preprocess(books, rates, users, nbRatings = 200, file_path="output.csv")

In [28]:
preprocessed.toPandas()

,Book-Title,ISBN,User-ID,Book-Rating,Book-Author,Year-Of-Publication,Publisher
0,Midnight,0425118703,278418,1,Dean R. Koontz,1995,Berkley Publishing Group
1,Midnight,0425118703,7346,1,Dean R. Koontz,1995,Berkley Publishing Group
2,Midnight,0425118703,11676,8,Dean R. Koontz,1995,Berkley Publishing Group
3,Midnight,0425118703,12538,9,Dean R. Koontz,1995,Berkley Publishing Group
4,Midnight,0425118703,31315,1,Dean R. Koontz,1995,Berkley Publishing Group
...,...,...,...,...,...,...,...
61771,Fast Food Nation: The Dark Side of the All-Ame...,0060938455,266865,10,Eric Schlosser,2002,Perennial
61772,Fast Food Nation: The Dark Side of the All-Ame...,0060938455,270713,2,Eric Schlosser,2002,Perennial
61773,Fast Food Nation: The Dark Side of the All-Ame...,0060938455,271448,2,Eric Schlosser,2002,Perennial
61774,Fast Food Nation: The Dark Side of the All-Ame...,0060938455,271705,2,Eric Schlosser,2002,Perennial
61775,Fast Food Nation: The Dark Side of the All-Ame...,0060938455,274004,10,Eric Schlosser,2002,Perennial

In [29]:
from src.preprocessing import pivot

In [30]:
pivot_df = pivot(preprocessed)

In [32]:
# Afficher le DataFrame pivoté
pivot_df.toPandas()

,Book-Title,254,2276,2766,2977,3363,3757,4017,4385,6242,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
0,Midnight,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,The Bridges of Madison County,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,6,0,0,0,1
2,"Loves Music, Loves to Dance",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,Mercy,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,2,0
4,The Pull of the Moon,0,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736,Jewel,0,0,0,0,0,0,10,0,0,...,0,0,0,0,0,0,0,0,0,0
737,Guilty as Sin,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
738,Confessions of an Ugly Stepsister : A Novel,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
739,Macgregor Brides (Macgregors),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
740,Fast Food Nation: The Dark Side of the All-Ame...,0,0,0,0,0,0,0,0,0,...,10,0,0,0,0,0,0,0,0,0

In [ ]:
spark.stop()